version: '3.6'
volumes:
  db_data:
  vendor:
services:
  php:
    build: .
    volumes:
      - ./docker/php/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - 80:80
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  pma:
     image: phpmyadmin/phpmyadmin:4.9
     ports:
       - 8080:80
