<?php

namespace Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use RefreshDatabase;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Artisan::call('migrate',['-vvv' => true]);
        \Artisan::call('db:seed',['-vvv' => true]);
        \Artisan::call('passport:install',['-vvv' => true]);
    }
}
